### PR TITLE
2839 Add resubmission sample data

### LINKED ISSUE #2839: Add resubmissions to sample data
We should update the sample data to include student resubmissions - assignments where they have submitted something, gotten a grade for it, and resubmitted it.

### PR DESCRIPTION
**Pull request by dovek**
### Status
**IN DEVELOPMENT**

### Description
Add Resubmissions to sample data

### Related PRs
N/A

### Todos
- [x] Let's add the assignment to all of the other courses (the courses represent different scenarios or Course-level feature variations, so we try to get the basic assignments, when appropriate, into each shell)
- [x] You added a pass/fail assignment, let's also create and add a graded assignment
- [x] The assignments should each be marked as "Accepting Submissions" - without that, you won't see the submission link on the assignment index, or the submission data on the grading page
- [x] The resubmissions should be marked as ungraded, meaning that they should appear on the Grading Status page and increase the alert number by that item in the menu

### Deploy Notes
N/A

### Gem dependencies
N/A

### Migrations
NO

### Steps to Test or Reproduce
Run
```
$ bundle exec rails db:sample --trace
```
in terminal.
Upon checking the database you should notice several records in the versions database for assignment with ID 475 that have updates submissions. The update will be for the link in the submission.

### Impacted Areas in Application
N/A

======================
Closes #2839

### CODE REVIEW

**Comment by chcholman** [comment]
@dovek Is this ready for review?

**Comment by dovek** [comment]
@chcholman Yes

**Comment by chcholman** [comment]
@dovek Thanks so much for this Kyle! A couple of changes to help make the data most useful as we use it to test throughout the app: 

- [ ] Let's add the assignment to all of the other courses (the courses represent different scenarios or Course-level feature variations, so we try to get the basic assignments, when appropriate, into each shell)
- [ ] You added a pass/fail assignment, let's also create and add a graded assignment
- [ ] The assignments should each be marked as "Accepting Submissions" - without that, you won't see the submission link on the assignment index, or the submission data on the grading page
- [ ] The resubmissions should be marked as ungraded, meaning that they should appear on the Grading Status page and increase the alert number by that item in the menu

Happy to talk through any of this in person today!

**Comment by chcholman** [comment]
@dovek This looks great, thanks so much Kyle!

**Pull request merged**
