### PR TITLE
Announcements

### PR DESCRIPTION
**Pull request by jwright**
This allows staff members to create announcements for a course. Those announcements get sent out to all students in the course via email when they are created.

Read/unread counts are kept track of for when students read an announcement.

This is the email that get's sent out to all students in the course. Only the first 25 words are displayed and then a link to the announcement show page is displayed. This will mark the announcement as read when the student visits that page.

screen shot 2015-08-16 at 2 19 21 pm

This is the announcement view page for a student with the new announcement indicator. Unread announcements are bold with a transparent row (a la Gmail):

screen shot 2015-08-16 at 2 19 52 pm

This is what the staff sees for creating new announcements:

screen shot 2015-08-16 at 2 20 50 pm

screen shot 2015-08-16 at 2 21 08 pm

### CODE REVIEW

**Comment by jwright** [comment]
@chcholman A few questions.

1. When a staff member is signed in, do they see all the announcements for the current course or just ones that they created?
1. When a student is signed in, do they see announcements for the context of the course they are in or all announcements that pertain to them?

**Comment by chcholman** [comment]
@jwright Hey! I just pulled this branch down to test, and none of the styling is appearing - any idea why that might be happening? I'm happy to debug on my side, but figured I'd ask first!

**Comment by jwright** [comment]
@chcholman The changes weren't in the master branch I pulled down yesterday. Did you just merge them in? There is a merge conflict now so I will get the latest and rebase.

**Comment by chcholman** [comment]
Yup, the merge conflict is my fault - I'm happy to do the rebase! I would have done it last night, but when I went to test the branch it appeared without any style sheets. I ran the migrations, ran bundle install, restarted the servers, but see this: 
screen shot 2015-08-17 at 8 32 49 am

**Comment by jwright** [comment]
@chcholman I rebased and changed the views to match the new css layout. The only issue is that now that we aren't using the Bootsy plugin for text areas, we can't create make rich text announcements. Do we have a plan for allowing rich text editing?

**Pull request merged**
