### PR TITLE
3930 learning objective show

### LINKED ISSUE #3929: Grade Show Page Should Show Learning Objective Assessment
The request is to show the learning objective assessment for _this_ assignment, _not_ the cumulative learning objective assessment (progress towards the total). That latter piece should be available via a link to the root learning objective where you can see the total progress - perhaps a hover state/card might be a way to visualize this without having it be the basic view of the page? Worth exploring.

### LINKED ISSUE #3930: Instructor Learning Objective Show page should have Indication of Progress
screen shot 2018-03-26 at 11 13 41 am

Shows 3000 points needed, versus the desired 3000/X points possible.

Also: 
- [x] Top align this table
- [x] Table of Student/progress/attempts should be sortable
- [x] Number of assignments currently to objective linked objective (new feature) (add in parentheses after the Linked Assignments (12) title)
- [x] Switch “in progress” to be a bar or some indicator of how far along the student is (in student view, shows x/y progress)

### LINKED ISSUE #4015: Turn Linked Assignments on the Learning Objective Overview page for students into a table
(all sortable)
Linked Assignment Name
Submitted (Y/N)
Assessment (Proficient/Not Proficient)
Resubmit (Y/N)

### LINKED ISSUE #4025: Student Learning Objective show page should show progress overview
"display X (number proficient) out of Y (total number needed)"

On each learning objective show page, also show this value, and make sure it's visible near to the top

Also: 

- [x] Top align this table
- [x] Add locked/key indicators to assignments 
- [x] Add visibility controls from the assignment index page 
- [x] Order assignments by assignment type, and then by instructor ordered position
- [x] If assignments have been submitted, add the date in the Submitted? column
- [x] If an assignment can be resubmitted, add that in the "Resubmit?" column

### LINKED ISSUE #4026: Link the Learning Objective title to the Learning Objective Description on the student show page

### PR DESCRIPTION
**Pull request by chcholman**
### Status
**READY**

### Description
This PR addresses #3930, revisions to the instructor learning objective show page, in addition to 

### Migrations
NO

### Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

1. 

### Impacted Areas in Application
List general components of the application that this PR will affect:

* Learning objectives - both instructor and student pages

======================
Closes #3930 
Closes #4025 
Closes #4015
Closes #4026
Closes #3929

### CODE REVIEW

**Comment by chcholman** [comment]
This is looking great!! 

One bug: 
- [ ] the student-side learning objective 'show' page breaks when there are now outcomes for the student

**Comment by jonathoy** [comment]
Any feedback that you guys can provide for this work would be great. I will merge when we are in agreement

**Comment by jonathoy** [comment]
@chcholman Are you looking at this view? I don't seem to be having any issues if so:

image

**Comment by chcholman** [comment]
@jonathoy Apologies, I had a typo in the previous note that confused things - yes, it works perfectly if the student has any learning objective outcomes in place. Check the view for a learning objective that the student has not yet started.

**Comment by chcholman** [comment]
I'm comfortable with this being merged as soon as this last fix is in place.

**Comment by jonathoy** [comment]
Fixed the issues. Noting here for the future that our objective show view is getting incredibly large and that we probably should split up some of the logic into two directives when we have time to refactor, since it is currently handling both the instructor and the student view.

**Comment by chcholman** [comment]
Confirmed that's fixed! Adding a ticket for the future that we should hide the Assignment table if there are none that meet it and replace it with "No assignments have been identified as meeting this objective - talk to your instructor for more information."

**Pull request merged**
