### PR TITLE
1994 student onboarding

### PR DESCRIPTION
**Pull request by mariehooper**
### Status
**READY**

### Description
This PR adds a series of slides to provide students who are new to GradeCraft with a quick, dismissible onboarding experience.

### Action items
- [x] remove ugly button from student dashboard and trigger modal on FIRST login for student.

screen shot 2016-11-16 at 6 05 16 pm

### Migrations
YES

### Impacted Areas in Application
List general components of the application that this PR will affect:

* student onboarding slides to show in modal over dashboard on first login

Closes issue #1994 #1879

### CODE REVIEW

**Comment by chcholman** [comment]
@mariehooper I've updated it so that we record whether or not a student has seen the onboarding panes, and they only see it if they have not yet confirmed receipt. Will you go through and test out the update, and break the `_student_onboarding.html.haml` file into multiple partials?

**Comment by mariehooper** [comment]
@acousticrobot - tagging you in this in case you don't get a notification for this comment: https://github.com/UM-USElab/gradecraft-development/pull/2663/commits/d83b533d8ce618b9d840e2712b4e3589424a2c9c

**Comment by mariehooper** [comment]
@chcholman - this should be ready for review. Huge thanks to you and @acousticrobot 🙌

**Comment by chcholman** [comment]
Looks fantastic, thanks to both of you for the excellent work! @mariehooper @acousticrobot

**Pull request merged**
