### PR TITLE
Improve instructions in README.md

### PR DESCRIPTION
**Pull request by peterkshultz**
Now, I'm not sure that my improved instructions are accurate. 

If they are not, tell me what kind of username has to be added. I'll make the necessary changes and open a new pull request.

### CODE REVIEW

**Comment by chcholman** [comment]
@peterkshultz It's closer to the first one - if you look at the line you're supposed to be updating here: 
https://github.com/peterkshultz/gradecraft-development/blob/8766d2f4e2f854424b63bd0557c545657545605a/config/database.yml.sample#L7 

You want to set it an admin username for the database you'll be running the app off of. Does that make sense?

**Comment by peterkshultz** [comment]
Hey there. I made a small syntactic change with the README.md to reflect what you commented 6 days ago--my apologies on not understanding that.

**Comment by chcholman** [comment]
Looks great, thanks @peterkshultz!

**Comment by peterkshultz** [comment]
@chcholman I was planning on animating the ellipses in the "Loading data, please wait..." messages to improve user experience. 

Is that something that would be of interest to you? I planned on opening the feature in a different pull request.

**Comment by chcholman** [comment]
@peterkshultz I think we'll leave those for now, thanks! 

Will you look through what you're seeing on the student side, and help me think through whether the text throughout makes sense?

**Comment by peterkshultz** [comment]
@chcholman Certainly! Any specific directories that I ought to take a look at?

**Pull request merged**
