### PR TITLE
Cache student sidebar

### PR DESCRIPTION
**Pull request by jwright**
This PR adds fragment caching focused on the student side. Since the student sidebar is rendered in almost every request for a student, this should be low-hanging fruit for response times.

I also added [Rack Mini Profiler](https://github.com/MiniProfiler/rack-mini-profiler) on development so that it shows the response time very easily.

Caching was enabled in the development environment as well.

Here is what the non-cached sql queries were before caching. (> 400 sql queries!):

screen shot 2015-09-17 at 9 23 19 am

Here is what the cached sql queries were after (~ 12 sql queries):

screen shot 2015-09-17 at 9 23 44 am

In order to test, you have to refresh a few times so that the fragment cache gets populated.

For testing, you want to ensure that the cache get's busted appropriately. Here is a list of some scenarios to test:

1. Add a student to a course and ensure that the course list in the top nav bar contains the new course
1. Change a course assignment due date and ensure that it reflects appropriately in the sidebar
1. Add/remove/update a badge and ensure that it reflects appropriately in the sidebar
1. Add an announcement and ensure that the announcement count increases by 1 in the tabs
1. Click on the announcement to read it and ensure that the announcement count decreases by 1 in the tabs

### CODE REVIEW

**Comment by chcholman** [comment]
Bug in the display of the course dropdown list 
screen shot 2015-09-17 at 3 32 34 pm

**Comment by jwright** [comment]
@chcholman I don't see the problem :)

**Comment by jwright** [comment]
@chcholman Ok. It was an issue of one too many indents

**Comment by chcholman** [comment]
There's a bug in the syllabus caching - look at the url (student id 10), and the link in the bottom left (I'm hovering over the 'grade' button, which should take me to the page to edit the grade for student 10 - the link shows 795). 
screen shot 2015-09-17 at 3 53 57 pm

**Comment by mlangens** [comment]
@chcholman I agree that it's better to separate the syllabus. I went ahead and reset that file to master

**Comment by chcholman** [comment]
Thanks so much @mlangens!

**Comment by chcholman** [comment]
Will you guys resolve the merge conflicts tomorrow?

**Comment by jwright** [comment]
@chcholman Sorry Cait. I just saw this. There are a lot of conflicts so this may take a while :(

**Comment by chcholman** [comment]
@jwright No worries! So sorry about all the conflicts :(

**Comment by jwright** [comment]
@chcholman Phew. Ok. Should be good now. Sorry about that.

**Comment by chcholman** [comment]
@jwright No worries at all! Thanks so much for doing that!

**Pull request merged**
