### PR TITLE
3441 learning objectives

### LINKED ISSUE #3441: Learning Objectives
Instructors need to be able to create them and attach them to multiple assignments 

Additions to the Course table/form:
- [ ] boolean turning on learning objectives as a feature
- [ ] Select form determining Learning Objectives name. Options: Learning Objectives, Learning Goals, Competencies, Standards
- [ ] Set count of how many yellow warnings are equal to a fail

New Learning Objectives Category Model:
- [ ] course_id
- [ ] name
- [ ] description

New Learning Objectives Model: 
- [ ] course_id
- [ ] name
- [ ] description
- [ ] learning objectives category id (optional)
- [ ] count to achieve

New Learning Objective Level Model: 
- [ ] course_id
- [ ] learning objective id
- [ ] name 
- [ ] description 
- [ ] flagged value - 1 (red card) or 2 (yellow card)

New Learning Objective Links Model: 
- [ ] course_id
- [ ] learning_objective_id
- [ ] learning_link_id 
- [ ] learning_link_type  (learning links need to be polymorphic, and account in the initial instance for both assignments and assignment types - this may expand to badges at some point)

New Learning Objectives Outcome Model: 
- [ ] course_id
- [ ] learning_objective_id 
- [ ] learning objective level id 
- [ ] assessment_id
- [ ] assessment_type  (Polymorphic, initially just referencing grades, may expand to earned badges) 
- [ ] assessed_at_date (manually set to map to the graded_at date)
- [ ] comments

Additional Tasks:
- [ ] Add Learning Objectives to the grading form
In a course where learning objectives have been created, they then need to appear in the grading form. For rubric grading, they'll appear at the top of the other rubric criterion. For standard grading, they'll appear beneath the points, but above the feedback form. **It is important that instructors be able to explicitly attach objectives to assignments but ALSO that they can grade any learning objective on any assignment if they exist**

- [ ] Add learning objective assessments to the grade show page 
If a student has been assessed on a learning objective as part of an assignment, that data then needs to be displayed on the grade show page

- [ ] Add learning objectives to the grade predictor page 
Learning objectives should be added to the assignment panel on the right side of the grade predictor page, highlighting what learning objectives an assignment explicitly satisfies

### PR DESCRIPTION
**Pull request by jonathoy**
### Status
READY

### Description
**For this initial round, the learning objective feature must both be enabled on the database side (`allows_learning_objectives` on Course model) as well as in Course settings.**

Start at Course Settings, where you can enable Learning Objectives for the course. You also have the ability to change the verbiage for learning objectives from the Advanced Settings pane.

Once enabled, you should notice a new option in the left-hand navbar for staff that corresponds to the selected term for learning objectives in the course. On this page you can view created learning objectives and categories, as well as create new or mass edit them in bulk.

Once you have created learning objectives, you can proceed to link them to specific assignments either from the a specific assignment's edit page or from the objective edit page.

Progress for the learning objectives will show on the grade show page for a student. You can click to see a detailed list of the linked assignments for that specific objective.

### Todos
- [ ] Improve Test Coverage
- [ ] Add Documentation
- [ ] Update Sample Data

### Deploy Notes
Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

### Migrations
YES

======================
Closes #3441

### CODE REVIEW

**Comment by chcholman** [comment]
UX Notes: 
- [ ] rename "Mass Edit" button to be "Quick Edit" (confirm with Evan)
- [ ] Description should be a (small) text box not a text field
- [ ] Add an info/help note to Count to Achieve
- [ ] Don't show category select list on the LO creation page if there are no categories 
- [ ] Add "Submit" buttons to each page, and confirm that they both submit the data and redirect you back to the LO page

**Comment by jonathoy** [comment]
@evanstraub Thanks for taking the time to look at this! I've addressed the feedback that you've provided by changing the create new learning objective form to be like the edit/edit all form. Let me know your thoughts. Can you also verify that the last bullet point that you added still is an issue? I wasn't able to replicate.

I would love for everyone to continue hammering away at this in staging as I make changes so that we can continue to work out bugs.

**Comment by evanstraub** [comment]
@jonathoy - the form now goes directly into the rubric building form, but I've now lost some of the functionality of the previous page (for example - I can't set the number of times to achieve the objective or the yellow card function).

More critical is that when I save the objective now, it just goes away?  
screen shot 2017-10-08 at 8 57 31 pm

**Comment by jonathoy** [comment]
Need to investigate why in Safari only, if you click on Save Changes on the objective edit form after making a change and before the changes have autosaved, an alert comes up saying that "An unexpected error occurred while saving"

**Comment by jonathoy** [comment]
@acousticrobot This is a rather large feature but I figure it would be good to have you glance over it if you have the chance.

I'm curious to know your thoughts on 0c98920. The problem Evan found was that in Safari, if you have started an AJAX call and a redirect or page refresh happens prior to completion, an HTTP status of 0 will return with null data. This technically falls into the failure block of any promise that is trigger via DebounceQueue.runAllEvents.

This bug was triggered on my branch, when editing an existing learning objective, making a bunch of changes and then clicking on Save Changes. I could see this happening elsewhere too.

**Comment by evanstraub** [comment]
Potential UX questions/issues.  Not sure how many will necessarily need to be addressed right now, but I wanted to put them out there.

- [ ] At the instructor level, there doesn't seem to be an easy way to see which assignments are associated with which LOs.  I could go in as a student and check, but maybe at the LO screen (or someplace) I should be able to see which assignments are associated with an LO without having to go into each assignment

- [ ] It would be really amazing  if I could associate assignments with LOs at the LO screen/interface rather than at each individual assignment.  As much as I know we'd like them to create LOs first, it's not always going to be the case.

- [ ]  When I look at an assignment that is associated with a LO, I see a page with ALL the LOs (which can be confusing) and it's not clear which one is associated with the particular assignment.  Nor does it appear that the "grade" (? not sure what to call it?) views for the student.  I couldn't tell which LOs were marked as "green" and which ones weren't.

- [ ] Does "green" mean they have achieved the learning objective?  Is that language going to be customizable?  I'd love to see that language customizable in some way.  I'm not sure "green" is going to make sense, or perhaps we can think about different ways to view that progress for the student?  While at the assignment level

- [ ] Is there a way we can scaffold or encourage faculty to directionally align their learning objectives a particular way?  I am anticipating that not all LOs will be set up in our preferred order, so I imagine that they may forget which side was "exceptional" vs "still trying"

**Comment by jonathoy** [comment]
@chcholman I made a few quick changes. For student side, I revised how progress is shown when they go to check out learning objectives from the navbar link. For the instructor side, I added an option to the learning objective view to see all linked assignments.

**Comment by jonathoy** [comment]
UX observations:

1. When I create a level and click the name field, the text cursor does not appear. It's missing the indication that I can start typing.

2. After I'm done editing a learning objective, I expected to return to the accordion category where I last was. Instead I'm brought to the LO index page with all accordions closed.

3. The empty state should offer a brief explanation/distinction of learning objectives used for assessment purposes, as well as a link to a set of example LOs.

4. The form for creating a new LO could be more consistent with other forms used in the app.

5. Consider integrating "categories" as a step in creating a new LO, rather than a prerequisite action (this would help users advanced towards their goal of creating a LO more readily).

6. "Add Levels" button could be more visible/prominent.

7. Consider making the "Options" button for each LO look more secondary to the primary action of adding a new LO. That way there's one clear primary action for the page. Secondary style = buttons with only blue outline and transparent background color.

**Comment by chcholman** [comment]
UX comments from @magyarn: 

UX observations:

- [ ] When I create a level and click the name field, the text cursor does not appear. It's missing the indication that I can start typing.

- [ ] After I'm done editing a learning objective, I expected to return to the accordion category where I last was. Instead I'm brought to the LO index page with all accordions closed.

- [ ] The empty state should offer a brief explanation/distinction of learning objectives used for assessment purposes, as well as a link to a set of example LOs.

- [ ] The form for creating a new LO could be more consistent with other forms used in the app.

- [ ] Consider integrating "categories" as a step in creating a new LO, rather than a prerequisite action (this would help users advanced towards their goal of creating a LO more readily).

- [ ] "Add Levels" button could be more visible/prominent.

- [ ] Consider making the "Options" button for each LO look more secondary to the primary action of adding a new LO. That way there's one clear primary action for the page. Secondary style = buttons with only blue outline and transparent background color.

**Comment by chcholman** [comment]
TO DO LIST 12/6: 

- [ ] We need a learning objectives "show" page. If you click on a learning objective as an instructor, it currently takes you to the "Edit" page. Let's leave that as the action that happens when you click edit, and add a new page that includes: 1) the learning objective name (as title), number of times/points to achieve, the description, the linked assignments, and a table with each student's progress. 

- [ ] Connect assignments to learning objectives via the Learning Objective form.

- [ ] Move the select list interaction for assignment links to be checkboxes instead

- [ ] Don't show the uncategorized assignment type by default - only if there are Learning Objectives with no category 

- [ ] Add the "Add Category" button (the box the with the dotted lines around it) to the bottom of the LO index page / outside of any other category (same as assignment types on the assignment index)

- [ ] Add persistence to the accordion on the LO index page (same as assignment)

- [ ] Add styling that indicates the "high" achievement is on the right, and the "low" achievement is on the left 

- [ ] The empty state should offer a brief explanation/distinction of learning objectives used for assessment purposes, as well as a link to a set of example LOs (ask Evan to write the copy here)

- [ ] Linked learning objectives are currently setting the `course_id` to be nil 

- [ ] Students should be able to click a learning objective and see the same show page as the instructor, but with their progress rather than other students' progress

--- 

We also need to sort out the color feature vs. competency achievement - I'll have more direction on that by Monday 12/11

**Comment by jonathoy** [comment]
I have some concerns about being able to
```
Connect assignments to learning objectives via the Learning Objective form.
```

as the form is already very complex. Any UX ideas as to how to best add this?

**Comment by chcholman** [comment]
@jonathoy Notes from this morning's review: 

- [ ] If there are no other learning objectives, the form you get is for learning objectives - let's start by giving them the Learning Objectives Category link instead 
- [ ] Don't show the Uncategorized section if there are no LOs in it (this is a repeat from above, but I am able to reproduce it, let me know if you want to see how)
- [ ] The LO show page should display the list of students and an empty table (we should talk to Evan about what should describe the "not yet started" state
- [ ] On the LO show page don't show the description if there isn't one
- [ ] On the LO show page don't show linked assignments if there aren't any 
- [ ] I think we've lost the ability to add linked assignments? 

Let's chat about the assignment form, and any other questions this morning!

**Comment by jonathoy** [comment]
@cait Just to be clear, for the first bullet you want to direct the user to first create a LO category?

**Comment by chcholman** [comment]
@jonathoy Yup, let's start showing them this: 

screen shot 2018-01-30 at 3 32 44 am

**Comment by jonathoy** [comment]
If you create a new course, the option to turn on learning objectives is there regardless of whether it is enabled in the backend.

**Comment by jonathoy** [comment]
- [ ] Ensure that learning objectives are not visible in any way to instructors and students if they have not been enabled. This pertains to courses that are not enabled on the backend as well as courses that have not had the setting turned on from the course settings page

- [ ] Test learning objectives with points vs no points, keeping in mind that this setting cannot be changed in course settings once one or more learning objectives exist. I'm happy to add in some sort of comment to this if it helps clarify

- [ ] Currently you can only link assignments to objectives one at a time from the assignment edit page. I am working on adding this ability to the objectives form. Once an assignment has been linked, ensure that you have the ability to assess the learning objective for a particular grade.

- [ ] As a student, once they have been assessed on a learning objective they should be able to see their progress not only from a status page accessible from the navigation bar but also from the show grade page.

**Comment by jonathoy** [comment]
@chcholman If you don't mind checking out the latest work that would be great. I see a few places where we can definitely streamline UX and improve upon some of the visual cues but I think it's at least ready for another review.

**Comment by chcholman** [comment]
Reviewing the absence of LOs this morning: 

- [ ] Sidebar "Learning Objectives" item for instructors is still showing, even if LOs are not allowed to be used in the course.

**Comment by jonathoy** [comment]
Latest changes:

- Linked assignments select dropdown on objective edit form is now grouped by assignment type. The assignments should already be sorted by their specified ordering.
- Default flagged value when creating a new learning objective level is now "Proficient"

**Pull request merged**
