### PR TITLE
Fix env variables

### PR DESCRIPTION
**Pull request by jwright**
This fixes several broken specs locally with some additions to the `.env` files.

This is an attempt to synchronize the necessary `.env` variables with what is being used in the application.

In addition, a spec that was breaking in Mac environments was fixed.

### CODE REVIEW

**Comment by jwright** [comment]
@acousticrobot Can you verify that this runs on your machine? 

@zazaian Please let me know if you see any issues with the `.env` variables.

**Comment by chcholman** [comment]
@zazaian Will you confirm that that works for you before I commit it?

**Comment by zazaian** [comment]
Sure thing @chcholman

**Comment by zazaian** [comment]
Running the specs now...

**Comment by zazaian** [comment]
@jwright @chcholman looks good on my end. Feel free to merge.

**Comment by chcholman** [comment]
@zazaian awesome, thanks.

**Pull request merged**
