### PR TITLE
Improve deactivation

### LINKED ISSUE #4193: Allow instructors to delete students, even if they have grades
### Expected Behavior
As an instructor, I expect that I should be able to delete a student from GradeCraft, especially in the use case where they've dropped my course. 

### Actual Behavior
Right now, we block the instructor from deleting students at all. 

### Steps to reproduce
Log in as an instructor, navigate to a student who has a grade in the course, attempt to delete them - no button. Significant testing should be done to ensure that in deleting the student's course_membership we also delete:

- [ ] submissions for the course
- [ ] submission_files
- [ ] grades for the course 
- [ ] predicted_earned_badges
- [ ] predicted_earned_challenges
- [ ] predicted_earned_grades
- [ ] earned_badges
- [ ] team_memberships
- [ ] team_leaderships
- [ ] criterion_grades
- [ ] announcement_states
- [ ] group_memberships
- [ ] assignment_type_weights
- [ ] flagged_users
- [ ] learning_objective_cumulative_outcomes
- [ ] learning_objective_observed_outcomes
- [ ] unlock_states

And that nothing else is harmed in the course. Particularly concerning is NOT deleting group_memberships if it were to invalidate the group, but instead prompting the instructor to manage the group first. Also, not deleting anything from any other course the student may be in!

┆Attachments: <a href="https://trello-attachments.s3.amazonaws.com/5a6f2020d4ad818ef1fffe12/5c461b15956a1b05bb7fd0b2/a5d5f58a3e2a7e94aeb12cd20475bee1/Screen_Shot_2019-09-05_at_5.12.07_PM.png">Screen Shot 2019-09-05 at 5.12.07 PM.png</a>

### PR DESCRIPTION
**Pull request by ebarroso7**
### Status
**READY**

### Description
Cleaning up the application so deactivated students actually appear to be removed from the course. 

What this doesn't do: 
Retroactively adjust groups that have students in them that have since group creation been deactivated.

Areas in the application:
* Exports
  * Final grades
  * Learning objectives
  * course grades
  * export of all the grades for a specific assignment type 
  * submissions export (assignment specific export of all submissions) 

* A specific assignment csv grade import template spreadsheet

* Adding members to a group selection box (editing/creating a group)

* Announcements table (who has read the announcement)  

* Assignment types dropdown on the analytics page 

* Grading status page (ungraded, in progress, resubmissions, ready for release) 

* Learning Objective overview page

* Refactors / changes some submission scopes into methods and makes new methods that check if the submission is for_active_student (same as the grades model) 

### Todos
- [x] test on staging

### Migrations
NO

### Steps to Test or Reproduce
Best way I found to test this was to deactivate an active student that has received grades and change their name to something more noticeable like "~~~~deactive student~~~~". 

======================
Closes #4193, #4474

### CODE REVIEW

**Comment by maskib** [comment]
@ebarroso7 Still seeing deactivated students on the LO overview page - e.g. Skib Music https://staging.gradecraft.com/learning_objectives/objectives/179

**Comment by maskib** [comment]
@ebarroso7 On the assignments page, if a category had grades/submissions for a student that was deactivated, and now the category has none, you still won't be able to delete it.

Screen Shot 2020-03-26 at 4 48 07 PM

**Comment by maskib** [comment]
@ebarroso7 Looks pretty good! There are a few places where I'm still finding deactivated students appearing: 

- Still seeing deactivated students on the LO overview page - e.g. Skib Music in 101 Michael Skib - testing: https://staging.gradecraft.com/learning_objectives/objectives/179
- On the assignments page, if a category had grades/submissions for a student that was deactivated, and now the category has none, you still won't be able to delete it. How would we want to handle a case like this?
- A deactivated student's submission still shows up in the submissions download for an assignment
- Ungraded submissions, in-progress grades and resubmissions from students who’ve been deactivated are still showing up on the grading status page.

**Comment by ebarroso7** [comment]
@maskib  Went 3 out of 4 on the issues you found, added to staging too! 

made an issue for the 4th one I didn't figure out yet https://github.com/UM-USElab/gradecraft-development/issues/4474

**Comment by maskib** [comment]
@ebarroso7 Was able to check this again today - noticed that on the [overall assignment page](https://staging.gradecraft.com/assignments), the number of submissions displayed for each assignment includes deactivated students, but the number of grades does not include deactivated students. This also appears to be true on the [Analytics pages](https://staging.gradecraft.com/per_assign).

Also, clicking "download grades" button on [that Analytics page](https://staging.gradecraft.com/per_assign) creates a .csv file report that includes deactivated students.

**Comment by ebarroso7** [comment]
@maskib good catch! Thank you!! Fixed and just pushed those changes to staging (:

**Pull request merged**
