### PR TITLE
Learning Objective Unlocks

### LINKED ISSUE #3836: Attach learning objectives to unlocks

### PR DESCRIPTION
**Pull request by jonathoy**
### Status
**NEEDS TESTING**

### Description
This PR adds the completion of a learning objective as an unlock for an assignment, badge, or grade scheme element.

Completion of a learning objective is defined by either the student achieving the count to achieve or points to completion value.

### Todos
- [x] Add Tests

### Migrations
NO

### Steps to Test or Reproduce

- [x] As a condition on an assignment, ensure that assignments lock/unlock as intended and that options such as visibility are enforced on the student-side
- [x] Repeat as a condition on a badge
- [x] Repeat as a condition on a grading scheme element

### Impacted Areas in Application
Grading + Learning objectives

======================
Closes #3836

### CODE REVIEW

**Comment by jonathoy** [comment]
Closes #4131

**Comment by maskib** [comment]
Hi all,

I'm not seeing the option to lock by Learning Objective in the list:

screen shot 2018-11-07 at 5 05 15 pm

Am I looking in the wrong place?

**Comment by maskib** [comment]
Indeed, the course allows for learning objectives. It's my test course, if you want to take a look at it: 
https://staging.gradecraft.com/courses/962/edit

**Comment by jlost** [comment]
I was able to find this. Maybe I'm missing something?

image

**Comment by maskib** [comment]
It seems like I can only link a learning objective to an assignment if that assignment has a point value greater than 0. Is that the desired behavior?

**Comment by jonathoy** [comment]
screen shot 2018-11-14 at 3 03 56 pm

@jlost Here's one place where we are not pulling in the custom term for learning objectives in the API call. A good way to test this is to go into `Course Settings -> Advanced Settings` and then select an alternative term like Competencies or Standards

**Comment by jlost** [comment]
I fixed the custom term and the zero-point inconsistency (by showing it in the edit page) if you want to take another look.

https://staging.gradecraft.com/learning_objectives/objectives/69/edit

https://staging.gradecraft.com/badges/1503/edit

**Comment by shaelynalbrecht** [comment]
Hi! The zero-point inconsistency seems to be fixed. Even if an assignment is worth 0 points, it still shows up as a choice to link when you’re editing your learning objective.

When selecting what my unlock condition was, the custom term (i used “competencies") still shows up as "learning objective" - here’s a screenshot when i was making an unlock condition for an assignment:
custom name for lo not showing up in unlock conditions dropdown

Additionally, when you’re grading assignments that are linked with learning objectives, if you’re using custom terms for LO’s, it shows up as Learning Objective in the header where you click to evaluate that student’s level:
custom name for lo not showing up in grading

**Comment by jlost** [comment]
Fixed those two problems.

**Comment by jlost** [comment]
I went ahead and fixed that one.

**Pull request merged**
