### PR TITLE
Student dashboard graded assignments and ungraded submissions table

### LINKED ISSUE #4194: Student ungraded submissions should be visible on the student dashboard
### Expected Behavior
Student's ungraded submissions should appear as a collapsible section in the table on the dashboard.

### Actual Behavior
Student's ungraded submissions are only visible in a table on the dashboard to instructors previewing as that student.

### Steps to reproduce
See #4125 - ideally this should be visible for students as well as instructors previewing as these students.

### PR DESCRIPTION
**Pull request by ebarroso7**
### Status
**READY**

### Description
This PR adds three tables to the bottom of the student dashboard page. These tables are very similar to the tables professors see when they look at a student (ex: 'students/9'), with a few minor changes. 

Things to discuss would be the content fo the tables like columns 

note - I chose to use another dynatable rather than try to work through the angular problems associated with modifying the grading status table that is used to populate the 'ungraded submissions' table for professors. 

### Todos
- [x] Converse about table content / language 
- [x] Test in staging
- [x] Check that the table does not appear if there are no items in it

### Migrations
NO

### Steps to Test or Reproduce
Log in as a student and view their dashboard. Now they have two tables at the bottom of this page. 

Tables to compare to this are on the professors 'grading status' page, and a professors view of a student ex: '.../students/6'. These tables are professor specific because they contain information regarding the whole class and grades that may not yet be visible to students. 

If you preview GC as a student, you see the same tables as the student.

======================
Closes #4194 #3454

### CODE REVIEW

**Comment by ebarroso7** [comment]
Hey @maskib ! Another PR to look at when you have the time! thanks again.

**Comment by maskib** [comment]
Question @ebarroso7 : should assignment submissions that have been marked graded but NOT visible to students yet show up in the "ungraded submissions" part of the dashboard? Currently graded submissions that aren't visible to students disappear from the "ungraded submissions" column, which could be confusing to students ("I thought I submitted this assignment but now I'm not seeing it in either table?")

**Comment by maskib** [comment]
Idea @ebarroso7 : the "graded submissions/assignments" table could include a column for badges awarded along with an assignment, if that course includes badges. Though, it might look weird, since most of the time that field would be empty.

**Comment by maskib** [comment]
@ebarroso7 Also, for assignments that allow for resubmission, once the assignment is resubmitted, should it move back to the "ungraded submissions" table? Currently it remains in the graded assignments table, which could make it seem like the resubmission has been graded, when it hasn't.

**Comment by maskib** [comment]
Currently submissions that are saved as drafts show up in the "ungraded submissions" table, regardless of whether the student has actually completed their submission. I'm guessing this is because a submission is automatically created in the database as soon as the submission is saved, so I'm not sure if there is a way around this.

**Comment by maskib** [comment]
@ebarroso7 Two entries will appear in the "ungraded submissions" table if:
1. A student creates a submission.
2. An instructor then edits that submission.
screen shot 2019-03-07 at 3 50 20 pm

**Pull request merged**
