### PR TITLE
Duplicate gradecraft events

### LINKED ISSUE #3011: Copy calendar events
### Expected Behavior
As an instructor I expect to be able to copy calendar events

### PR DESCRIPTION
**Pull request by dovek**
### Status
**IN DEVELOPMENT**

### Description
As an instructor I expect to be able to duplicate calendar events

### Related PRs
N/A

### Todos
- [x] Add Tests

### Deploy Notes
N/A

### Gem dependencies
N/A

### Migrations
NO

### Steps to Test or Reproduce
As an instructor, navigate to the event show page of the event you would like to duplicate. In the top right corner of the page, click the "Duplicate Event" button. View the database to assure that your event has indeed been duplicated.

### Impacted Areas in Application
List general components of the application that this PR will affect:

* Events

======================
Closes #3011

### CODE REVIEW

**Comment by dovek** [comment]
@jonathoy Presenter tests passed this time. I agree the issue is intermittent but I'd feel more confident if I knew why they failed at times.

**Comment by chcholman** [comment]
@dovek @jonathoy I made a tiny (_tiny_) tweak tot he language on this PR. Are you ready for me to merge it?

**Comment by dovek** [comment]
@chcholman I am, yes.

**Comment by chcholman** [comment]
@dovek Awesome, thanks!

**Pull request merged**
