### PR TITLE
1276 assignments controller

### LINKED ISSUE #1276: Test coverage for Assignments Controller

### PR DESCRIPTION
**Pull request by jwright**
This improves the test coverage and increases the GPA grade for the `AssignmentsController`.

Reduced the line count for all methods (except `export_submissions`) to be below 8 lines which should improve complexity.

`export_submissions` was not included as it is fixed in the [`smart_archiver`](https://github.com/UM-USElab/gradecraft-development/tree/smart_archiver) branch.

Closes #1276

### CODE REVIEW

**Comment by jwright** [comment]
@chcholman This seems like a very weird method as it updates the `id` column for assignments (I didn't know you could do that :/). I can't find anywhere where it is being used. Do you know if it is being used off-hand?

https://github.com/UM-USElab/gradecraft-development/blob/master/app/controllers/assignments_controller.rb#L123

**Comment by chcholman** [comment]
@jwright Ah. No, that's not the goal... It's definitely being used - it is supposed to update the _position_ of the assignment and can be manipulated by loading the assignment index, and drag/drop reordering the assignment in the list. You'll find the same 'sort' method on badges, and assignment types.

**Comment by jwright** [comment]
@chcholman Ok. I will update it and write a test for it :)

**Comment by jwright** [comment]
@chcholman Also, I read it wrong. It is updating the `position` attribute.

**Comment by chcholman** [comment]
@jwright (phew)

**Pull request merged**
