### PR TITLE
Ability to add badge feedback for awarding badges, during assignment grading

### LINKED ISSUE #4314: When awarding a badge while grading an assignment, it should be possible to provide badge feedback
### Expected Behavior
* When awarding a badge while grading an assignment as an instructor, it should be possible to provide badge feedback for the awarded badge.

### Actual Behavior
* Currently there is no way to provide badge feedback for the awarded badge.

### Steps to reproduce
* As an instructor, grade an assignment and award a badge. It is not possible to provide badge feedback for the awarded badge.

### PR DESCRIPTION
**Pull request by adishy**
### Status
**READY**

### Description
* When grading an assignment as an instructor it should be possible to leave feedback for awarding a badge without leaving the assignment grading view
* Now awarding a badge for a student while grading an assignment displays a text input for providing feedback for the badge. Any existing feedback for a badge can also be edited in this view.

### Migrations
NO

### Steps to Test or Reproduce
1. As an instructor, grade an assignment and award a badge to a student. Once the checkbox for a badge has been selected, a text box will appear below the list of badges for entering feedback about the badge that was awarded.

### Impacted Areas in Application
* "Award Badges" section wile grading an assignment (i.e.directives/grades/earned_badges_select.coffee, /services/BadgeService.coffee, app/controllers/api/earned_badges_controller.rb)
* config/routes.rb for updating feedback for EarnedBadges using PUT api/earned_badges/<id>
======================
Closes #4314

### CODE REVIEW

**Comment by maskib** [comment]
@adishy This works great in terms of the functionality described, but now I'm trying to figure out where I ought to be able to view that badge related feedback, both as a student, and as an instructor? I'm not finding it.

**Comment by adishy** [comment]
@maksib 
The feedback for the badge provided by the instructor will show up:

**for students:**
In the page for viewing the badge for the student, click on badges in the sidebar and click on the newly awarded badge. The feedback will be displayed under the "Awarded" section.  (/badges/\<badge-id\>). 

**for staff:**
Similarly visit (/badges/\<badge-id\>). The badge feedback will appear next to the student's name in list displayed.

**Comment by maskib** [comment]
Thanks, I see them now!

**Comment by ebarroso7** [comment]
Looks good to me! Thanks for digging through that angular stuuufff @adishy

**Pull request merged**
